### ISSUE TITLE
Load crash

### ISSUE THREAD

**Issue by al-wei** [Invadermonky/JustEnoughMagiculture#12]
https://github.com/Invadermonky/JustEnoughMagiculture/issues

**Comment by Invadermonky** [comment]
The link you provided redirects to JEM's issue page. Please submit a crashlog.

**Comment by al-wei** [comment]
> The link you provided redirects to JEM's issue page. Please submit a crashlog.

Sorry for copying the wrong link.
https://gist.github.com/al-wei/32bb386cc4a85f78ecc2a0f63ab5cafa

**Comment by al-wei** [comment]
> The link you provided redirects to JEM's issue page. Please submit a crashlog.

Oh, there's another mod for you to work on.
https://legacy.curseforge.com/minecraft/mc-mods/villager-market-nbt-fix/issues

**Comment by al-wei** [comment]
Conflict with Elemental Items.

https://www.curseforge.com/minecraft/mc-mods/elemental-items/screenshots

**Comment by Invadermonky** [comment]
I have been unable to reproduce the crash in any of my environments. As of version  [1.12.2-1.2.0](https://www.curseforge.com/minecraft/mc-mods/just-enough-magiculture/files/5787394) I forced JEM to load after Elemental Items which may fix the issue.

**Comment by al-wei** [comment]
> I have been unable to reproduce the crash in any of my environments. As of version [1.12.2-1.2.0](https://www.curseforge.com/minecraft/mc-mods/just-enough-magiculture/files/5787394) I forced JEM to load after Elemental Items which may fix the issue.

Version 1.2 successfully entered the game.
1.1.5:Version 1.1.5, still crashes when loaded alone.
https://mclo.gs/wceKj1F

**Comment by Invadermonky** [comment]
If the crash is no longer occurring then I am going to close this comment as fixed/complete as of version [1.12.2-1.2.0](https://www.curseforge.com/minecraft/mc-mods/just-enough-magiculture/files/5787394).
