### ISSUE TITLE
Load crash

### ISSUE THREAD

**Issue by al-wei** [Invadermonky/JustEnoughMagiculture#15]
justenoughmagiculture-1.12.2-1.1.5

https://mclo.gs/eq0LiKu
beastslayer-2.0.test_1.04

**Comment by Invadermonky** [comment]
Due to the Beast Slayer author completely changing the structure of his mod during the 2.0 update as well as an issue with versioning during the alpha releases, Just Enough Magiculture does not support the most recent beta releases (2.0.x).

**Comment by Invadermonky** [comment]
[1.12.2-1.2.0](https://www.curseforge.com/minecraft/mc-mods/just-enough-magiculture/files/5787394)
