### ISSUE TITLE
iaf rl crash

### ISSUE THREAD

**Issue by al-wei** [Invadermonky/JustEnoughMagiculture#16]
https://mclo.gs/9LK7oti

**Comment by Invadermonky** [comment]
Ice and Fire RLCraft Edition is extremely outdated and will not be supported by Just Enough Magiculture. Use either the original [Ice and Fire: Dragons](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons) or [Ice and Fire: RotN Edition](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-rotn-edition).

**Comment by al-wei** [comment]
> Ice and Fire RLCraft Edition is extremely outdated and will not be supported by Just Enough Magiculture. Use either the original [Ice and Fire: Dragons](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons) or [Ice and Fire: RotN Edition](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-rotn-edition).

rl version September 30, recently updated.
Just no Dragonsteel content.

**Comment by al-wei** [comment]
> Ice and Fire RLCraft Edition is extremely outdated and will not be supported by Just Enough Magiculture. Use either the original [Ice and Fire: Dragons](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons) or [Ice and Fire: RotN Edition](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-rotn-edition).

Although I think that after the rl version update, there should be all the content, just no Dragonsteel.
If you think it's outdated, forget it.
