### ISSUE TITLE
1.2.0 bugged

### ISSUE THREAD

**Issue by xJon** [Invadermonky/JustEnoughMagiculture#17]
The mod appears to only partially work, the config file doesn't generate and the mod doesn't show up in-game.
Reproduced on its own. Downgrading to `1.1.5` resolves these issues.

**Comment by Invadermonky** [comment]
Looks like the file got corrupted on upload. New version uploaded [1.12.2-1.2.1](https://www.curseforge.com/minecraft/mc-mods/just-enough-magiculture/files/5796192).
