### ISSUE TITLE
Crash with Planar Artifice: Continuation

### ISSUE THREAD

**Issue by Margatroidu** [Invadermonky/JustEnoughMagiculture#18]
Crash with [Planar Artifice: Continuation](https://www.curseforge.com/minecraft/mc-mods/planar-artifice)

[crash-2024-10-25_09.56.38-client.txt](https://github.com/user-attachments/files/17517671/crash-2024-10-25_09.56.38-client.txt)

**Comment by Invadermonky** [comment]
Nothing about this crash log has anything to do with Just Enough Magiculture and I am unable to reproduce the crash.

**Comment by Margatroidu** [comment]
> Nothing about this crash log has anything to do with Just Enough Magiculture and I am unable to reproduce the crash.

Yes, judging by the logs this error is caused by another mod. Then I'm closing this issue
