### ISSUE TITLE
Crash with last version of Beast Slayer

### ISSUE THREAD

**Issue by Margatroidu** [Invadermonky/JustEnoughMagiculture#20]
Crash with Beast Slayer [beastslayer-2.0.test_1.041]

[crash-2024-11-17_11.06.53-client.txt](https://github.com/user-attachments/files/17789581/crash-2024-11-17_11.06.53-client.txt)

**Comment by Invadermonky** [comment]
I see the issue, Beast Slayer changed the name of that single configuration for ...some reason (***internal screaming***).

I'm a little busy at the moment so the fix is a while out.

**Comment by Margatroidu** [comment]
> The configuration option field name has been reverted. This crash should be fixed in the next Beast Slayer update.

Yeah, it seems to be working.
