### ISSUE TITLE
Quark's Tallow not showing as pig drop

### ISSUE THREAD

**Issue by xJon** [Invadermonky/JustEnoughMagiculture#8]
Is enabled & working in-game, yet there's no JEI integration.

**Comment by Invadermonky** [comment]
Quark adds the tallow drop not as part of the loottable but instead injects the drop during the LivingDropsEvent. [see here](https://github.com/Rebirth-of-the-Night/Quark/blob/5e56338063d8006f77c089828527146d08eb1fcd/src/main/java/vazkii/quark/decoration/feature/TallowAndCandles.java#L68)

I'll add the tallow drop in the next update.

**Comment by Invadermonky** [comment]
Fixed as of version 1.1.4. Release has been submitted to Curseforge.
