### ISSUE TITLE
Crash on startup with Mystcraft (not sure)

### ISSUE THREAD

**Issue by Margatroidu** [Invadermonky/JustEnoughMagiculture#9]
Last version crashes on sturtup in my modpack. I'm not quite sure if the problem is caused by mystcraft or not, but the crash report mentions this mod 

[crash-2024-05-13_12.54.02-client.txt](https://github.com/Invadermonky/JustEnoughMagiculture/files/15292734/crash-2024-05-13_12.54.02-client.txt)

**Comment by Invadermonky** [comment]
Fixed with version 1.12.2-1.1.5
